const actionTypes={
    telephoneaction:{
        GET_TELEPHONES_START:"GET_TELEPHONES_START",
        GET_TELEPHONES_SUCCESS:"GET_TELEPHONES_SUCCESS",
        GET_TELEPHONES_FAİL:"GET_TELEPHONES_FAİL",
        DELETE_TELEPHONES_START:"GET_TELEPHONES_START",
        DELETE_TELEPHONES_SUCCESS:"GET_TELEPHONES_SUCCESS",
        DELETE_TELEPHONES_FAİL:"GETY_TELEPHONES_FAİL",
        ADD_TELEPHONES:"ADD_TELEPHONES"
    },
    groupaction:{
        GET_GROUPS_START:"GET_GROUPS_START",
        GET_GROUPS_SUCCESS:"GET_GROUPS_SUCCESS",
        GET_GROUPS_FAİL:"GET_GROUPS_FAİL"        
        }
}

export default actionTypes;